[package]
name = "example"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = { version = "0.8.9", features = ["http2"] }
beeper = { path = "../beeper", features = ["h1", "h2"] }
http = "1.5"
tokio = { version = "1.53", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
libc = "0.2.189"
anyhow = "1.0.104"
xbpf = "0.0.3"

[build-dependencies]
xbpf = { version = "0.0.3", features = ["build"] }
beeper = { path = "../beeper", features = ["build"] }
