[package]
name = "utils"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.104"
as-bytes = "0.2.0"
axum = { version = "0.8.9", features = ["http2"] }
beeper = { path = "../beeper", features = ["h1", "h2"] }
bytes = "1.12.1"
libc = "0.2.189"
tokio = { version = "1.53", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
xbpf = "0.0.4"

[build-dependencies]
xbpf = { version = "0.0.4", features = ["build"] }
beeper = { path = "../beeper", features = ["build"] }
